- name: converge
  hosts: all
  roles:
    - role: ansible_tower
  vars:
    ansible_tower_no_log: false
    ansible_tower_inventory_file: ../default/inventory
    ansible_tower_extra_vars:
      admin_username: admin
      admin_password: notsecure
      pg_password: notsecure
    ansible_tower_license_path: ../default/license.json
    ansible_tower_host: "{{ ansible_default_ipv4.address }}"
    ansible_tower_validate_certs: false
    ansible_tower_organization: oasis
    ansible_tower_inventory: oasis-test
    ansible_tower_scm_url: https://github.com/ansible/test-playbooks.git
    ansible_tower_scm_branch: master
    ansible_tower_project: test-playbooks
    ansible_tower_job_template: test-ansible_env
    ansible_tower_playbook: ansible_env.yml
    ansible_tower_job_timeout: 120

  tasks:
    - name: Set the license using a file
      awx.awx.tower_license:
        data: "{{ lookup('file', '{{ ansible_tower_license_path }}') }}"
        eula_accepted: true
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"

    - name: Create tower organization
      tower_organization:
        name: "{{ ansible_tower_organization }}"
        state: present
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"

    - name: Add tower inventory
      tower_inventory:
        name: "{{ ansible_tower_inventory }}"
        organization: "{{ ansible_tower_organization }}"
        state: present
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"

    - name: Add tower host
      tower_host:
        name: localhost
        inventory: "{{ ansible_tower_inventory }}"
        state: present
        variables:
          ansible_connection: local
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"

    - name: Add tower project
      tower_project:
        name: "{{ ansible_tower_project }}"
        organization: "{{ ansible_tower_organization }}"
        state: present
        scm_update_on_launch: true
        scm_branch: "{{ ansible_tower_scm_branch }}"
        scm_type: git
        scm_url: "{{ ansible_tower_scm_url }}"
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"

    - name: Create tower job template
      tower_job_template:
        name: "{{ ansible_tower_job_template }}"
        job_type: "run"
        inventory: "{{ ansible_tower_inventory }}"
        project: "{{ ansible_tower_project }}"
        playbook: "{{ ansible_tower_playbook }}"
        state: "present"
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"

    - name: Launch the test job
      tower_job_launch:
        job_template: "{{ ansible_tower_job_template }}"
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"
      register: _ansible_tower_job
      changed_when: false

    - name: Wait for job
      tower_job_wait:
        job_id: "{{ _ansible_tower_job.id }}"
        timeout: "{{ ansible_tower_job_timeout }}"
        validate_certs: "{{ ansible_tower_validate_certs }}"
        tower_host: "{{ ansible_tower_host }}"
        tower_username: "{{ ansible_tower_extra_vars.admin_username }}"
        tower_password: "{{ ansible_tower_extra_vars.admin_password }}"
      register: _ansible_tower_job_status

    - name: Display job status
      debug:
        msg: "{{ _ansible_tower_job_status }}"
